#! /usr/bin/bash

function main()
{
  # tests all sid files in test specified directories
  declare -a dirs scripts results
  dirs=( . .. )
  scripts=(  )
  results=(  )
  i=0
  for dir in ${dirs[@]}
  do
    # the ? prevents pickup of the sid script itself
    for script in $dir/?*sid
    do
      ../sid $script
      ret=$?
      print_result $script $ret

      scripts[$i]="$script"
      results[$i]=$ret
      let "i = $i + 1"
    done
  done
  
  echo 
  echo Results of test run:
  count=${#results[@]}
  i=0
  while [ $i -lt $count ]
  do
      script=${scripts[$i]}
      result=${results[$i]}
      print_result $script $result
      let "i = $i + 1"
  done
}

function print_result()
{
    script=$1
    result=$2
    if [[ $result -gt 0 ]]; then
      echo -e "script $script: \033[0;31mFAILED\033[0m"
    else
      echo -e "script $script: \033[0;32mPASSED\033[0m"
    fi

}

main